Customer_Management/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("web.urls", namespace="web")),
    path("users/", include("users.urls", namespace="users")),
    path('posts/', include("posts.urls", namespace="posts")),
]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

posts/urls.py
from django.urls import path, include,re_path
from posts import views


app_name = "posts"

urlpatterns = [
    path('create/', views.create_event, name="create_post"),
    path('edit/<uuid:pk>/', views.edit_event, name="edit_event"),
    path('delete/<uuid:pk>/', views.delete_event, name='delete_event'),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views


app_name = 'users'
urlpatterns = [
    path("login/", views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
]

web/urls.py
from django.contrib import admin
from django.urls import path
from web import views

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
]

templates/web/includes/header.html
{% load static %}
<header>
    <div class="logo">
        <h1>
            <a href="{% url 'web:index' %}">
                <img
                    src="{% static 'images/logo.svg' %}"
                    alt="Logo"
                />
            </a>
        </h1>
    </div>
    <div class="right">
        {% if request.user.is_authenticated %}
        <a style="margin-right: 16px;"  href="{% url 'posts:create_post' %}" class="btn">Add Events</a>
        <a href="{% url 'users:logout' %}" class="btn logout"> Logout </a>
        {% else%}
            <a href="{% url 'users:login' %}" class="btn login"> Login </a>
        {% endif %}
    <div>
</header>