Customer_Management/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("web.urls", namespace="web")),
    path("users/", include("users.urls", namespace="users")),
    path('posts/', include("posts.urls", namespace="posts")),
]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

posts/urls.py
from django.urls import path, include,re_path
from posts import views


app_name = "posts"

urlpatterns = [
    path('create/', views.create_event, name="create_post"),
    path('edit/<uuid:pk>/', views.edit_event, name="edit_event"),
    path('delete/<uuid:pk>/', views.delete_event, name='delete_event'),
]

web/urls.py
from django.contrib import admin
from django.urls import path
from web import views

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
]

templates/web/index.html
{% extends 'base.html' %}
{% block content %}
{% load static%}
<section id="home">
    <section class="wrapper">
        {% include 'web/includes/header.html' %}

        <section class="spotlight">
            <h3>Events</h3>
            <div class="all-posts">
                <div class="post-section">
                    <ul class="posts">
                        {% for event in events %}
                        <li>
                            <a href="{% url 'posts:edit_event' pk=event.pk %}">
                                {% if event.image %}
                                <div class="blog-image">
                                    <img src="{{event.image.url}}" alt="Blog" />
                                </div>
                                {% endif %}
                                <div class="details">
                                    <div class="date">
                                        <h4 class="name">{{event.event_type}}</h4>
                                        <div class="round"></div>
                                        <span> {{event.event_date|date:"D d/m/Y"}} </span>
                                    </div>
                                </div>
                            </a>
                        </li>
                        {% endfor %}                        
                    </ul>
                    
                </div>
                <div class="filter-section" id="hamburger-menu">
                    <form action="">
                        <p class="filter-head">Sort by</p>
                        <div class="filter">
                            <label class="radio">
                                <input type="radio" name="sort" value="today" />
                                <span class="radio"></span>
                                <span class="label">Today</span>
                            </label>
                            <label class="radio">
                                <input type="radio" name="sort" value="week" />
                                <span class="radio"></span>
                                <span class="label">This Week</span>
                            </label>
                            <label class="radio">
                                <input type="radio" name="sort" value="month" />
                                <span class="radio"></span>
                                <span class="label">This Month</span>
                            </label>
                            
                        </div>
                    
                        
                        <input type="submit" value="Filter" />
                    </form>
                </div>
            </div>
        </section>
    </section>
</section>
{% endblock %}