Customer_Management/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("web.urls", namespace="web")),
    path("users/", include("users.urls", namespace="users")),
    path('posts/', include("posts.urls", namespace="posts")),
]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views


app_name = 'users'
urlpatterns = [
    path("login/", views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
]

web/urls.py
from django.contrib import admin
from django.urls import path
from web import views

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
]

users/models.py
from django.db import models

# Create your models here.
  

users/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    name = forms.CharField(max_length=30, required=True)
    phone_number = forms.CharField(max_length=15, required=True)
    email = forms.EmailField(max_length=254, required=False)
    dob = forms.DateField(
        required=True, widget=forms.DateInput(attrs={'type': 'date'}))
    address = forms.CharField(max_length=200, required=True)

    class Meta:
        model = User
        fields = ['name', 'phone_number',
                  'email', 'dob', 'address', 'password']
    widgets = {
        "password": forms.widgets.PasswordInput(attrs={"placeholder": "Enter strong password"}),
        "name": forms.widgets.TextInput(attrs={"placeholder": "Enter your name"}),
        "dob": forms.widgets.DateInput(attrs={"type": "date", "placeholder": "DD/MM/YYYY"}),
        "address": forms.widgets.TextInput(attrs={"placeholder": "Enter your address"}),
        "email": forms.widgets.EmailInput(attrs={"placeholder": "Enter your email(optional)", "required": False}),

    }

users/views.py
from django.shortcuts import render, reverse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.http.response import HttpResponseRedirect
from django.contrib.auth.models import User


from main.functions import generate_form_errors
from posts.forms import CustomerForm


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)

                return HttpResponseRedirect("/")

        context = {
            "title": "Login",
            "error": True,
            "message": "Invalid username or password !!!"
        }
        return render(request, "users/login.html", context=context)
    else:
        context = {
            "title": "Login"
        }
        return render(request, "users/login.html", context=context)


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse("users:login"))


def signup(request):
    if request.method == "POST":
        form = CustomerForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            # print(form.cleaned_data)
            form_data = form.cleaned_data
            
            if User.objects.filter(username=form_data['username']):
                form = CustomerForm(instance=instance)
                context = {
                    "title": "Signup",
                    "error": True,
                    "message": "User with username already exists",
                    "form": form,
                }
                return render(request, "users/signup.html", context=context)
            else:
                new_user = User.objects.create_user(
                    username=form_data['username'],
                    password=form_data['password'],
                    email=form_data['email'],
                    first_name=form_data['first_name'],
                    last_name=form_data['last_name']
                )
                instance.user = new_user
                instance.save()         

            user = authenticate(
                request, username=form_data['username'], password=form_data['password'])
            auth_login(request, user)

            return HttpResponseRedirect(reverse("web:index"))

        else:
            message = generate_form_errors(form)

            form = CustomerForm()
            context = {
                "title": "Signup",
                "error": True,
                "message": message,
                "form": form,
            }
            return render(request, "users/signup.html", context=context)

    else:
        form = CustomerForm()
        context = {
            "title": "Signup",
            "form": form,
        }
        return render(request, "users/signup.html", context=context)

templates/users/auth_base..html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <title>{{title}}</title>
    <link rel="stylesheet" type="" href="{% static 'css/auth_style.css' %}" />
    <link
      rel="shortcut icon"
      href="{% static 'images/logo.svg' %}"
      type="image/svg"
    />
  </head>
  <body>
    {% block content %} {% endblock %}
</body>
</html>

templates/users/auth_base.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <title>{{title}}</title>
    <link rel="stylesheet" type="" href="{% static 'css/auth_style.css' %}" />
    <link
      rel="shortcut icon"
      href="{% static 'images/logo.svg' %}"
      type="image/svg"
    />
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

templates/users/login.html
{% extends "users/auth_base.html" %} {% block content %} {% load static %}
<div class="login-box">
  <h2>Customer Login</h2>
  <form method="post" action="" class="ajax">
    {% csrf_token %}
    <div class="user-box">
      <input type="text" name="username" required="" />
      <label>Username</label>
    </div>
    <div class="user-box">
      <input type="password" name="password" required="" />
      <label>Password</label>
    </div>
    <input class="button" type="submit" value="Login" />
    <a class="button register" href="{% url 'users:signup' %}">Register</a>
    <a class="forgot" href="#">Forgot Password ?</a>
  </form>
  <div class="submit">
    {% if error %}
    <p
      style="
        font-size: 14px;
        color: red;
        text-align: center;
        margin: 18px 0;
        font-weight: 800;
      "
      class="error-message"
    >
      {{message}}
    </p>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/users/signup.html
{% extends "users/auth_base.html" %} {% block content %} {% load static %}
<div class="signup-form">
  <h2>Create an account</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group">
          <label" for="{{field.id_for_label}}">{{field.label}}</label>
          {{field}}
      </div>
    {% endfor %}
    <div class="form-group">
      {% if error %}
        <p class="error-message">{{message}}</p>
      {% endif %}
      <input style="margin-bottom: 16px;" type="submit" value="Create Account" class="button">
      <a class="button" href="{% url 'users:login' %}">Login</a>
    </div>
  </form>
</div>
{% endblock %}